alias c='echo External IP:;curl -4 icanhazip.com'
alias ll='ls -la'
alias lh='ls -lah'
alias lt='ls -lart'
alias ltg='ls -lart | grep -i $1'
alias nsg='netstat -nap | grep -i $1'
alias psg='ps -ef | grep -i $1'
alias findgrep='find / | egrep -i $1'
alias cya='shutdown -h now'
alias h='history'
alias histgrep='history | egrep -i $1'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias ports='netstat -tulanp'
alias p='ping 8.8.8.8 -c 1; ping yahoo.com -c 1'
alias bwt='wget http://cachefly.cachefly.net/100mb.test -O /dev/null'
alias av='source .venv/bin/activate'
alias dv='deactivate'
alias gfp='find `pwd` -name $1'

# Django
alias pm='python manage.py $*'
alias pmr='python manage.py runserver'
alias pms='python manage.py shell'
alias pmcs='python manage.py collectstatic --noinput'
alias pmrl='python manage.py runserver --settings=config.settings.local'
alias pmrp='python manage.py runserver --settings=config.settings.production'
alias rundj='python manage.py runserver 0.0.0.0:8000'
alias tp='echo "Running Django triple play...";python manage.py makemigrations django_scantron;python manage.py makemigrations;python manage.py migrate'
alias newdb='cd /var/www/webapp;pkill python;sudo -i -u postgres dropdb scantron;sudo -i -u postgres createdb scantron;rm -rf scantron/migrations/*;tp;python manage.py createsuperuser --username admin'
